apiVersion: v1
kind: PersistentVolume
metadata:
  name: codeserver-local-pv
  labels:
    app: codeserver
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/tempura/codeserver
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - it-sushi-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: codeserverconf-local-pv
  labels:
    app: codeserverconf
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/tempura/.config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - it-sushi-1