apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-local-pvc
  namespace: codeserver
  labels:
    app: codeserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  selector:
    matchLabels:
      app: codeserver
  storageClassName: local-storage 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserverconf-local-pvc
  namespace: codeserver
  labels:
    app: codeserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  selector:
    matchLabels:
      app: codeserverconf
  storageClassName: local-storage