apiVersion: v1
kind: Service
metadata:
  name: codeserver
  namespace: codeserver
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.31
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: codeserver
 