apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.33
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: pgadmin
 