apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-local-pvc
  namespace: emby
  labels:
    app: emby
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 
  selector:
    matchLabels:
      app: emby
  storageClassName: local-storage 