apiVersion: v1
kind: PersistentVolume
metadata:
  name: embymedia-local-pv
  labels:
    app: emby
spec:
  capacity:
    storage: 300Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /hdd/media/emby/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - it-sushi-1