apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: emby
spec:
  selector:
    app: emby
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8096
      name: http
    - protocol: TCP
      port: 443
      targetPort: 8920
      name: https
  type: LoadBalancer
  loadBalancerIP: 10.0.0.42