apiVersion: v1
kind: PersistentVolume
metadata:
  name: technitium-local-pv
  labels:
    app: technitium
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /hdd/volumes/technitium
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - it-sushi-1