apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: 'Survival'
          - name: MOTD
            value: 'Sushi Server!'
          - name: ALLOW_FLIGHT
            value: 'FALSE'
          - name: OPS
            value: 'Housentax'
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath: /data
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-local-pvc
    