apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-local-pvc
  namespace: minecraft
  labels:
    app: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
  selector:
    matchLabels:
      app: minecraft
  storageClassName: local-storage 