apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.40
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: minecraft
 