apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.32
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
 